### ISSUE TITLE
error when running parGOSim()

### ISSUE THREAD

**Issue by deniseduma** [road2stat/protr#24]
Hi,

I'm trying to use the function parGOSim(). However, when running the example in the vignette on my Linux machine 

genelist = list(c("150", "151", "152", "1814", "1815", "1816"))
gsimmat2 = parGOSim(genelist, type = "gene")
print(gsimmat2)

I get the following error:

Error in GOSemSim::mgeneSim(unlist(golist), ont = ont, organism = organism,  : 
  unused arguments (ont = ont, organism = organism)

It seems that somehow the call to a function in the GOSemSim package goes wrong. 

Could you please fix this problem in protr so I can use parGOSim()? 

Thank you,
Denise

**Comment by road2stat** [comment]
Hi @deniseduma -thanks for the feedback! It looks like the `twoGOSim` and `parGOSim` function and code examples are both not working due to some upstream API changes. I've just updated them all and submitted a new version to CRAN (v1.6-0). Before the new version is available on CRAN, you can try the GitHub version with `devtools::install_github("road2stat/protr")`. Hope this helps! -Nan

**Comment by deniseduma** [comment]
Thank you!!
